config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'posts#index'

  resources :profile, :only => [:show, :follow, :unfollow] do
    member do
      put "follow", to: "profile#follow"
      put "unfollow", to: "profile#unfollow"
    end
  end
  
  mount Commontator::Engine => '/commontator'

  resources :posts


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mention.rb
class Mention < Socialization::ActiveRecordStores::Mention
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  validates_presence_of :ime, :opis
  validates :ime, length: { maximum: 25 }
  validates :opis, length: { minimum: 15, message: 'Prosim vnesite daljši opis' }

  acts_as_commontable dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_follower
  acts_as_followable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy

  acts_as_commontator
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password)}

      devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password)}
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :can_access?, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    def can_access?
      redirect_back fallback_location: root_path, alert: 'You shall not pass!' unless @post.user == current_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:ime, :opis)
    end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  before_action :authenticate_user!, only: [:follow, :unfollow]
  before_action :set_user, only: [:show, :follow, :unfollow]
  before_action :prevent_self_follow, only: [:follow, :unfollow]
  def show
    @posts = Post.includes(:user).where(user_id: params[:id])
  end

  def follow
    current_user.follow!(@user)
    redirect_back(fallback_location: root_path)
end

def unfollow
    current_user.unfollow!(@user)
    redirect_back(fallback_location: root_path)
end

private
  def set_user
    @user = User.find(params[:id])
  end

  def prevent_self_follow
    redirect_to root_path, notice: "You can't do that." if @user == current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def show_notice
    if notice.present?
      "<p id='notice' class='alert alert-success' role='alert'>#{notice}</p>".html_safe
    end
  end

  def show_alert
    if alert.present?
      "<p id='alert' class='alert alert-danger' role='alert'>#{alert}</p>".html_safe
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def show_post_buttons(post)
    html = '<td>'
    html += link_to 'Show', post
    html += '</td>'
    if post.user == current_user
      html += '<td>'
      html += link_to 'Edit', edit_post_path(post)
      html += '</td>'
      html += '<td>'
      html += link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }
      html += '</td>'
    end

    html.html_safe
  end

  def show_edit_button(post)
    link_to 'Edit', edit_post_path(post) if post.user == current_user
  end
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <li class="nav-item active">
        <% if user_signed_in? %>
          <%= link_to "Profile", profile_path(current_user), class: 'nav-link' %>
        <% end %>
      </li>

      <li class="nav-item active">
        <%= link_to 'Home', root_path, class: 'nav-link' %>
      </li>
      <li class="nav-item active">
      
      </li>
      <li class="nav-item active">
        <% if user_signed_in? %>
          <%= link_to('Logout', destroy_user_session_path, method: :delete, class: 'nav-link') %>
        <% else %>
          <%= link_to('Login', new_user_session_path, class: 'nav-link') %>
        <% end %>
      </li>

      

    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= show_notice %>
      <%= show_alert %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :ime %>
    <%= form.text_field :ime %>
  </div>

  <div class="field">
    <%= form.label :opis %>
    <%= form.text_area :opis, rows: 5, cols: 60, required: true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Objave</h1>

<%= link_to 'Nova objava', new_post_path %>
<br><br>
<div class="row">
  <% @posts.each do |post| %>
    <div class="col-md-12">
      <div class="card flex-md-row mb-4 box-shadow h-md-250">
        <div class="card-body d-flex flex-column align-items-start">
          <strong class="d-inline-block mb-2 text-primary"><%= post.user.name %></strong>
          <div class="mb-1 text-muted"><%= post.created_at.strftime('%d. %m. %Y')%></div>
          <p class="card-text mb-auto"><%= post.opis %></p>
        </div>  
      </div>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p>
  <strong>Ime:</strong>
  <%= @post.ime %>
</p>

<p>
  <strong>Opis:</strong>
  <%= @post.opis %>
</p>
<p>
  <strong>Napisal:</strong>
  <%= @post.user.name %>
</p>

<%= show_edit_button(@post) %> |
<%= link_to 'Back', posts_path %>

<%= commontator_thread(@post) %>